---
forgejo_runner_has_pkg: false
forgejo_runner_pkg_name: forgejo-runner
forgejo_runner_pkg_user: forgejo-runner
forgejo_runner_pkg_group: "{{ forgejo_runner_pkg_user }}"
forgejo_runner_gnupg_package: gnupg2
